name: Manage by Discussion
description: "Manage contributor vouch status via discussion comments (vouch/denounce/unvouch)."

inputs:
  comment-node-id:
    description: "GraphQL node ID of the discussion comment."
    required: true
  discussion-number:
    description: "Discussion number."
    required: true
  allow-denounce:
    description: "Enable denounce handling to denounce users."
    required: false
    default: "true"
  allow-unvouch:
    description: "Enable unvouch handling to remove users."
    required: false
    default: "true"
  allow-vouch:
    description: "Enable vouch keyword handling to vouch for contributors."
    required: false
    default: "true"
  denounce-keyword:
    description: "Comma-separated list of keywords that trigger denouncing (default: denounce)."
    required: false
    default: ""
  dry-run:
    description: "Print what would happen without making changes."
    required: false
    default: "false"
  repo:
    description: "Repository in 'owner/repo' format (default: current repository)."
    required: false
    default: ""
  unvouch-keyword:
    description: "Comma-separated list of keywords that trigger unvouching (default: unvouch)."
    required: false
    default: ""
  vouch-keyword:
    description: "Comma-separated list of keywords that trigger vouching (default: vouch)."
    required: false
    default: ""
  vouched-file:
    description: "Path to the vouched contributors file (empty = auto-detect)."
    required: false
    default: ""

outputs:
  status:
    description: "Result status: vouched, denounced, unvouched, or unchanged"
    value: ${{ steps.run.outputs.status }}

runs:
  using: composite
  steps:
    - uses: hustcer/setup-nu@v3
      with:
        version: "*"

    - id: run
      shell: nu {0}
      run: |
        use "${{ github.action_path }}/../../vouch" *

        let vouch_kw = "${{ inputs.vouch-keyword }}" | split row "," | each { str trim } | where { $in | is-not-empty }
        let denounce_kw = "${{ inputs.denounce-keyword }}" | split row "," | each { str trim } | where { $in | is-not-empty }
        let unvouch_kw = "${{ inputs.unvouch-keyword }}" | split row "," | each { str trim } | where { $in | is-not-empty }

        let status = (gh-manage-and-push
          --type "discussion"
          --id ${{ inputs.discussion-number }}
          --comment-id "${{ inputs.comment-node-id }}"
          --repo "${{ inputs.repo || github.repository }}"
          --vouched-file "${{ inputs.vouched-file }}"
          --vouch-keyword $vouch_kw
          --denounce-keyword $denounce_kw
          --unvouch-keyword $unvouch_kw
          --allow-vouch=(${{ inputs.allow-vouch }} | into bool)
          --allow-denounce=(${{ inputs.allow-denounce }} | into bool)
          --allow-unvouch=(${{ inputs.allow-unvouch }} | into bool)
          --dry-run=(${{ inputs.dry-run }} | into bool)
        )
        $"status=($status)" | save --append $env.GITHUB_OUTPUT

    - if: inputs.dry-run == 'false'
      shell: nu {0}
      run: |
        use "${{ github.action_path }}/../../vouch"

        let vouched_file = if ("${{ inputs.vouched-file }}" | is-empty) {
          vouch default-path
        } else {
          "${{ inputs.vouched-file }}"
        }

        let is_new = (git ls-files $vouched_file | str trim | is-empty)
        if $is_new {
          git add $vouched_file
        }

        let diff = git diff --quiet $vouched_file | complete
        if $diff.exit_code == 0 and not $is_new {
          print "No changes to commit"
          exit 0
        }

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add $vouched_file
        let url = $"($env.GITHUB_SERVER_URL)/${{ inputs.repo || github.repository }}/discussions/${{ inputs.discussion-number }}#discussioncomment-${{ inputs.comment-node-id }}"
        git commit -m $"Update VOUCHED list\n\n($url)"

        let attempts = 0
        let max_attempts = 5
        while $attempts < $max_attempts {
            let push_result = (git push | complete)
            if $push_result.exit_code == 0 {
                print "Successfully pushed changes."
                break
            } else {
                print $"Git push failed (attempt ($attempts + 1)/($max_attempts)). Error: ($push_result.stderr)"
                print "Attempting to rebase and retry..."
                let pull_result = (git pull --rebase | complete)
                if $pull_result.exit_code != 0 {
                    error $"Git pull --rebase failed: ($pull_result.stderr)"
                }
            }
            $attempts = $attempts + 1
        }

        if $attempts == $max_attempts {
            error "Failed to push changes after multiple attempts."
        }
